language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - docker --version # print the version for logging
  - docker-compose version

script:
  - docker-compose -f docker-compose-build.yaml build --parallel

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mcl1011/udagram-api-user:v4c
  - docker push mcl1011/udagram-api-feed:v4b
  - docker push mcl1011/udagram-frontend:local
  - docker push mcl1011/udagram-reverseproxy:v4a
