version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: udagram-reverseproxy:v4a
  backend-user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user:v4c
  backend-feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed:v4b
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local